name: La Tinaja
description: "My name is Brian Jones. These are my notes on topics including books, publishing, tech, and history."
plugins:
  - jekyll-paginate
paginate: 15
url: http://tinaja.computer
markdown: kramdown
collections:
  - books
